export const POSTULER_OFFRE_REQUEST = 'POSTULER_OFFRE_REQUEST';
export const POSTULER_OFFRE_SUCCESS = 'POSTULER_OFFRE_SUCCESS';
export const POSTULER_OFFRE_FAIL = 'POSTULER_OFFRE_FAIL';
export const POSTULER_OFFRE_RESET = 'POSTULER_OFFRE_RESET';

export const GET_CANDIDATURES_REQUEST = 'GET_CANDIDATURES_REQUEST';
export const GET_CANDIDATURES_SUCCESS = 'GET_CANDIDATURES_SUCCESS';
export const GET_CANDIDATURES_FAIL = 'GET_CANDIDATURES_FAIL';
export const GET_CANDIDATURES_RESET = 'GET_CANDIDATURES_RESET';

export const ANNULER_CANDIDATURE_REQUEST = 'ANNULER_CANDIDATURE_REQUEST';
export const ANNULER_CANDIDATURE_SUCCESS = 'ANNULER_CANDIDATURE_SUCCESS';
export const ANNULER_CANDIDATURE_FAIL = 'ANNULER_CANDIDATURE_FAIL';
