export const POSTULER_OFFRE_REQUEST = 'POSTULER_OFFRE_REQUEST';
export const POSTULER_OFFRE_SUCCESS = 'POSTULER_OFFRE_SUCCESS';
export const POSTULER_OFFRE_FAIL = 'POSTULER_OFFRE_FAIL';
export const POSTULER_OFFRE_RESET = 'POSTULER_OFFRE_RESET';

export const GET_CANDIDATURES_REQUEST = 'GET_CANDIDATURES_REQUEST';
export const GET_CANDIDATURES_SUCCESS = 'GET_CANDIDATURES_SUCCESS';
export const GET_CANDIDATURES_FAIL = 'GET_CANDIDATURES_FAIL';
export const GET_CANDIDATURES_RESET = 'GET_CANDIDATURES_RESET';

export const ANNULER_CANDIDATURE_REQUEST = 'ANNULER_CANDIDATURE_REQUEST';
export const ANNULER_CANDIDATURE_SUCCESS = 'ANNULER_CANDIDATURE_SUCCESS';
export const ANNULER_CANDIDATURE_FAIL = 'ANNULER_CANDIDATURE_FAIL';

export const GET_CANDIDATURES_OFFER_REQUEST = 'GET_CANDIDATURES_OFFER_REQUEST';
export const GET_CANDIDATURES_OFFER_SUCCESS = 'GET_CANDIDATURES_OFFER_SUCCESS';
export const GET_CANDIDATURES_OFFER_FAIL = 'GET_CANDIDATURES_OFFER_FAIL';
export const GET_CANDIDATURES_OFFER_RESET = 'GET_CANDIDATURES_OFFER_RESET';

export const GET_CANDIDATURE_DETAIL_REQUEST = 'GET_CANDIDATURE_DETAIL_REQUEST';
export const GET_CANDIDATURE_DETAIL_SUCCESS = 'GET_CANDIDATURE_DETAIL_SUCCESS';
export const GET_CANDIDATURE_DETAIL_FAIL = 'GET_CANDIDATURE_DETAIL_FAIL';
export const GET_CANDIDATURE_DETAIL_RESET = 'GET_CANDIDATURE_DETAIL_RESET';

export const GET_CANDIDATURE_OWNER_CV_REQUEST =
  'GET_CANDIDATURE_OWNER_CV_REQUEST';
export const GET_CANDIDATURE_OWNER_CV_SUCCESS =
  'GET_CANDIDATURE_OWNER_CV_SUCCESS';
export const GET_CANDIDATURE_OWNER_CV_FAIL = 'GET_CANDIDATURE_OWNER_CV_FAIL';

export const GET_CANDIDATURE_OWNER_PDP_REQUEST =
  'GET_CANDIDATURE_OWNER_PDP_REQUEST';
export const GET_CANDIDATURE_OWNER_PDP_SUCCESS =
  'GET_CANDIDATURE_OWNER_PDP_SUCCESS';
export const GET_CANDIDATURE_OWNER_PDP_FAIL = 'GET_CANDIDATURE_OWNER_PDP_FAIL';

export const CHANGE_STATUS_CANDIDATURE_REQUEST =
  'CHANGE_STATUS_CANDIDATURE_REQUEST';
export const CHANGE_STATUS_CANDIDATURE_SUCCESS =
  'CHANGE_STATUS_CANDIDATURE_SUCCESS';
export const CHANGE_STATUS_CANDIDATURE_FAIL =
  'CHANGE_STATUS_CANDIDATURE_REQUEST';
