export const OFFRES_LIST_REQUEST = 'OFFRES_LIST_REQUEST';
export const OFFRES_LIST_SUCCESS = 'OFFRES_LIST_SUCCESS';
export const OFFRES_LIST_FAIL = 'OFFRES_LIST_FAIL';

export const OFFRES_LIST_ADMIN_REQUEST = 'OFFRES_LIST_ADMIN_REQUEST';
export const OFFRES_LIST_ADMIN_SUCCESS = 'OFFRES_LIST_ADMIN_SUCCESS';
export const OFFRES_LIST_ADMIN_FAIL = 'OFFRES_LIST_ADMIN_FAIL';

export const OFFRE_DELETE_REQUEST = 'OFFRE_DELETE_REQUEST';
export const OFFRE_DELETE_SUCCESS = 'OFFRE_DELETE_SUCCESS';
export const OFFRE_DELETE_FAIL = ' OFFRE_DELETE_FAIL';

export const OFFRE_VALIDATE_REQUEST = 'OFFRE_VALIDATE_REQUEST';
export const OFFRE_VALIDATE_SUCCESS = 'OFFRE_VALIDATE_SUCCESS';
export const OFFRE_VALIDATE_FAIL = 'OFFRE_VALIDATE_FAIL';

export const OFFRES_LIST_RECRUTEUR_REQUEST = 'OFFRES_LIST_RECRUTEUR_REQUEST';
export const OFFRES_LIST_RECRUTEUR_SUCCESS = 'OFFRES_LIST_RECRUTEUR_SUCCESS';
export const OFFRES_LIST_RECRUTEUR_FAIL = 'OFFRES_LIST_RECRUTEUR_FAIL';

export const OFFRE_CREATE_REQUEST = 'OFFRE_CREATE_REQUEST';
export const OFFRE_CREATE_SUCCESS = 'OFFRE_CREATE_SUCCESS';
export const OFFRE_CREATE_FAIL = 'OFFRE_CREATE_FAIL';
export const OFFRE_CREATE_RESET = 'OFFRE_CREATE_RESET';

export const OFFRE_DETAIL_REQUEST = 'OFFRE_DETAIL_REQUEST';
export const OFFRE_DETAIL_SUCCESS = 'OFFRE_DETAIL_SUCCESS';
export const OFFRE_DETAIL_FAIL = 'OFFRE_DETAIL_FAIL';

export const LATEST_OFFERS_REQUEST = 'LATEST_OFFERS_REQUEST';
export const LATEST_OFFERS_SUCCESS = 'LATEST_OFFERS_SUCCESS';
export const LATEST_OFFERS_FAIL = 'LATEST_OFFERS_FAIL';

export const CLOTURER_OFFRE_REQUEST = 'CLOTURER_OFFRE_REQUEST';
export const CLOTURER_OFFRE_SUCCESS = 'CLOTURER_OFFRE_SUCCESS';
export const CLOTURER_OFFRE_FAIL = 'CLOTURER_OFFRE_FAIL';
export const CLOTURER_OFFRE_REST = 'CLOTURER_OFFRE_RESET';
