export const OFFRES_LIST_REQUEST = 'OFFRES_LIST_REQUEST';
export const OFFRES_LIST_SUCCESS = 'OFFRES_LIST_SUCCESS';
export const OFFRES_LIST_FAIL = 'OFFRES_LIST_FAIL';

export const OFFRES_LIST_ADMIN_REQUEST = 'OFFRES_LIST_ADMIN_REQUEST';
export const OFFRES_LIST_ADMIN_SUCCESS = 'OFFRES_LIST_ADMIN_SUCCESS';
export const OFFRES_LIST_ADMIN_FAIL = 'OFFRES_LIST_ADMIN_FAIL';

export const OFFRE_DELETE_REQUEST = 'OFFRE_DELETE_REQUEST';
export const OFFRE_DELETE_SUCCESS = 'OFFRE_DELETE_SUCCESS';
export const OFFRE_DELETE_FAIL = ' OFFRE_DELETE_FAIL';

export const OFFRE_VALIDATE_REQUEST = 'OFFRE_VALIDATE_REQUEST';
export const OFFRE_VALIDATE_SUCCESS = 'OFFRE_VALIDATE_SUCCESS';
export const OFFRE_VALIDATE_FAIL = 'OFFRE_VALIDATE_FAIL';

export const OFFRES_LIST_RECRUTEUR_REQUEST = 'OFFRES_LIST_RECRUTEUR_REQUEST';
export const OFFRES_LIST_RECRUTEUR_SUCCESS = 'OFFRES_LIST_RECRUTEUR_SUCCESS';
export const OFFRES_LIST_RECRUTEUR_FAIL = 'OFFRES_LIST_RECRUTEUR_FAIL';
