export const OFFRES_LIST_REQUEST = 'OFFRES_LIST_REQUEST';
export const OFFRES_LIST_SUCCESS = 'OFFRES_LIST_SUCCESS';
export const OFFRES_LIST_FAIL = 'OFFRES_LIST_FAIL';

export const OFFRE_DELETE_REQUEST = 'OFFRE_DELETE_REQUEST';
export const OFFRE_DELETE_SUCCESS = 'OFFRE_DELETE_SUCCESS';
export const OFFRE_DELETE_FAIL = ' OFFRE_DELETE_FAIL';
