export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const USER_LIST_REQUEST = 'USERS_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_RESET = 'USER_LIST_RESET';
export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = ' USER_DELETE_FAIL';

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAIL = 'USER_INFO_FAIL';
export const USER_INFO_RESET = 'USER_INFO_RESET';

export const USER_CHANGE_ROLE_REQUEST = 'USER_CHANGE_ROLE_REQUEST';
export const USER_CHANGE_ROLE_SUCCESS = 'USER_CHANGE_ROLE_SUCCESS';
export const USER_CHANGE_ROLE_FAIL = 'USER_CHANGE_ROLE_FAIL';
export const USER_CHANGE_ROLE_RESET = 'USER_CHANGE_ROLE_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_FAIL';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET';

export const GET_USER_IMAGE_REQUEST = 'GET_USER_IMAGE_REQUEST';
export const GET_USER_IMAGE_SUCCESS = 'GET_USER_IMAGE_SUCCESS';
export const GET_USER_IMAGE_FAIL = 'GET_USER_IMAGE_FAIL';
export const GET_USER_IMAGE_RESET = 'GET_USER_IMAGE_RESET';

export const GET_USER_CV_REQUEST = 'GET_USER_CV_REQUEST';
export const GET_USER_CV_SUCCESS = 'GET_USER_CV_SUCCESS';
export const GET_USER_CV_FAIL = 'GET_USER_CV_FAIL';

export const GET_LOG_REQUEST = 'GET_LOG_REQUEST';
export const GET_LOG_SUCCESS = 'GET_LOG_SUCCESS';
export const GET_LOG_FAIL = 'GET_LOG_FAIL';
export const GET_LOG_RESET = 'GET_LOG_RESET';
